---
chdir: /home/deployer/helmos/current/
environment: staging
address: 0.0.0.0
port: 3000
timeout: 30
log: /home/deployer/helmos/shared/log/thin_staging.log
pid: /home/deployer/helmos/tmp/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
servers: 3
daemonize: true
onebyone: true
ssl: false
